import 'package:flutter_app/models/user_data.dart';

/// Represents a single scored feature from the AI analysis.
class ScoredFeature {
  final int score;
  final String explanation;

  ScoredFeature({required this.score, required this.explanation});

  factory ScoredFeature.fromJson(Map<String, dynamic> json) {
    return ScoredFeature(
      score: (json['score'] as num).toInt(),
      explanation: json['explanation'] as String,
    );
  }
}

/// Represents a detailed analysis of a match between two users,
/// generated by the backend AI service.
class MatchAnalysis {
  final String id; // Unique ID for this specific match analysis
  final UserData userA; // The current user
  final UserData userB; // The matched user

  /// A witty, one-sentence summary of the match.
  final String matchSummary;

  /// A holistic AI-generated compatibility score (0.0 to 1.0).
  final double totalScore;

  /// A breakdown of compatibility across different traits, with scores.
  /// e.g., {'Creative Spark': ScoredFeature(score: 90, explanation: '...')}
  final Map<String, ScoredFeature> similarFeatures;

  MatchAnalysis({
    required this.id,
    required this.userA,
    required this.userB,
    required this.totalScore,
    required this.matchSummary,
    this.similarFeatures = const {},
  });

  factory MatchAnalysis.fromJson(Map<String, dynamic> json) {
    final totalScoreRaw = json['finalScore'] ?? json['totalScore'] ?? 0;
    double score = (totalScoreRaw as num).toDouble();
    if (score > 1.0) {
      score = score / 100.0;
    }

    final featuresRaw = json['similarFeatures'];
    final similarFeatures = <String, ScoredFeature>{};
    if (featuresRaw is Map<String, dynamic>) {
      featuresRaw.forEach((key, value) {
        if (value is Map<String, dynamic>) {
          similarFeatures[key] = ScoredFeature.fromJson(value);
        }
      });
    } else if (featuresRaw is List) {
      for (var i = 0; i < featuresRaw.length; i++) {
        final entry = featuresRaw[i];
        if (entry is Map<String, dynamic>) {
          final label = entry['label']?.toString() ?? 'Trait ${i + 1}';
          similarFeatures[label] = ScoredFeature.fromJson(entry);
        }
      }
    }

    return MatchAnalysis(
      id: json['id'] ?? 'unknown_match',
      userA: UserData.fromJson(
          Map<String, dynamic>.from(json['userA'] as Map? ?? const {})),
      userB: UserData.fromJson(
          Map<String, dynamic>.from(json['userB'] as Map? ?? const {})),
      totalScore: score.clamp(0.0, 1.0), // Ensure score is within valid range
      matchSummary:
          json['summary'] ?? json['matchSummary'] ?? 'No summary available',
      similarFeatures: similarFeatures,
    );
  }
}
